[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/nodemailer/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
